version: 2

project_name: vdradmin-go

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vdradmin
    main: ./cmd/vdradmin
    binary: vdradmin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  disable: false

release:
  draft: false
  prerelease: auto
